<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Bold.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-BoldItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Italic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Regular.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Black.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BlackItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Bold.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BoldItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Italic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Light.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-LightItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Medium.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-MediumItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Regular.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Thin.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-ThinItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Bold.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-BoldItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Italic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Light.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-LightItalic.ttf" />
    <Content Remove="C:\Users\DELL\.nuget\packages\materialdesignthemes\5.3.1\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\logo.ico" />
    <None Remove="Resources\Icons\NumidixLogoSQR256.ico" />
    <None Remove="Resources\Icons\NumidixLogoSQR32.ico" />
    <None Remove="Resources\Icons\NumidixLogoSQR64.ico" />
    <None Remove="Resources\Photos\NumidixLogoSQR.png" />
    <None Remove="Resources\Photos\Shiakati beige Logo horiz.png" />
    <None Remove="Resources\Photos\Shiakati beige Logo horizental.png" />
    <None Remove="Resources\Photos\Shiakati beige Logo.png" />
    <None Remove="Resources\Photos\shiakati bg.png" />
    <None Remove="Resources\Photos\Shiakati Black and white - VERTICAL.png" />
    <None Remove="Resources\Photos\Shiakati Black and white.png" />
    <None Remove="Resources\Photos\Shiakati Dark Logo.jpg" />
    <None Remove="Resources\Photos\Shiakati Light Logo.jpg" />
    <None Remove="Resources\Photos\shiakati logo on secondary brush.png" />
    <None Remove="ToDo.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icons\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\logo.ico" />
    <Resource Include="Resources\Icons\NumidixLogoSQR256.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Icons\NumidixLogoSQR32.ico" />
    <Resource Include="Resources\Icons\NumidixLogoSQR64.ico" />
    <Resource Include="Resources\Photos\Shiakati Black and white - VERTICAL.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Photos\Shiakati Black and white.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Photos\shiakati logo on secondary brush.png" />
    <Resource Include="ToDo.txt">
      <Generator>MSBuild:Compile</Generator>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.14" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Photos\NumidixLogoSQR.png" />
    <Resource Include="Resources\Photos\Shiakati beige Logo horiz.png" />
    <Resource Include="Resources\Photos\Shiakati beige Logo horizental.png" />
    <Resource Include="Resources\Photos\Shiakati beige Logo.png" />
    <Resource Include="Resources\Photos\shiakati bg.png" />
    <Resource Include="Resources\Photos\Shiakati Dark Logo.jpg" />
    <Resource Include="Resources\Photos\Shiakati Light Logo.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsetting.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
